export const tagLang=[
    {zh:"登录",en:"Login",id:"loginpage_name",type:"text"},
    {zh:"请选择语言",en:"Select language",id:"loginpage_language",type:"input"},
    {zh:"请输入密码",en:"Input password",id:"loginpage_password",type:"input"},
    {zh:"开始配网",en:"Connect",id:"start-connect",type:"text"},
    {zh:'密码6-8位，支持数字、大小写字母和特殊字符',en:'Password 6-8 digits, supports numbers, upper and lower case letters and special characters',id:'passwordprompt',type:'text'},
    {zh:'忘记密码',en:'Forget password',id:'forgetpassword',type:'text'},
    {zh:'登录',en:'Login',id:'loginpage_submit',type:'text'},
]
export const promptInfo={
    prompt:{zh:"提示",en:"Prompt"},
    confirm:{zh:"确定",en:"OK"},
    cancel:{zh:"取消",en:"Cancel"},
    requestFailed:{zh:"数据请求失败",en:"Data request failed"},
    connectFailed:{zh:"配网失败, 请重试",en:"Connection failed"},
    connectTimeout:{zh:"配网超时, 请重试",en:"Connection timeout"},
    connectSuc:{zh:"配网成功",en:"Connection succeeded"},
    upgradeFailed:{zh:"升级失败，请稍后重试",en:"Upgrade failed. Please try again later."},
    enterSsid:{zh:"请输入热点名称",en:"Please enter SSID"},
    ssidError:{zh:"输入的热点名称过长，请保持在32个字节之内",en:"The SSID is too long. Please keep it within 32 bytes"},
    passwordError:{zh:"输入密码过长，请保持在64个字节之内",en:"Password is too long. Please keep it within 64 bytes"},
    closedWeb:{zh:'配网成功',en:'Connection succeeded'},
    wifiList:{zh:"Wi-Fi 列表",en:"Wi-Fi List"},
    partitionList:{zh:"分区列表",en:"Partition List"},
    refresh:{zh:"刷新",en:"Refresh"},
    getWifiFailed:{zh:"获取 Wi-Fi 列表失败",en:"Failed to get Wi-Fi AP list"},
    getPartitionFailed:{zh:"获取分区列表失败",en:"Failed to get partition list"},  //没找到
    enterPartition:{zh:"请选择分区",en:"Please select partition"},
    noData:{zh:"暂无数据",en:"No data available"},
    selectFile:{zh:"请选择文件",en:"Please select file"},
    formatError:{zh:"选择的文件格式有误",en:"Incorrect file format"},
    fileLarge:{zh:"选择的文件过大，请选择小于 2MB 的文件",en:"File is too large. Please select a file less than 2MB."},
    getVersionFailed:{zh:"获取固件版本失败",en:"Failed to get firmware version"},
    otaSuc:{zh:"升级成功",en:"OTA Succeeded"},
    otaFailed:{zh:"升级失败，请稍后重试",en:"OTA Failed"}
}